// Lightweight Jest mock for LangChain agents used in server AI integration tests
// Returns deterministic, small responses so tests don't call external OpenAI services.

const routerAgent = {
  invoke: async (_messages) => {
    // Very small heuristic: return a stable classification for tests
    return { classification: 'scenery_or_general_subject' };
  }
};

const sceneryAgent = {
  invoke: async (_messages) => {
    // Return a JSON payload in kwargs.content that the parser expects
    return {
      kwargs: {
        content: JSON.stringify({
          caption: 'Mocked scenery caption',
          description: 'This is a mocked description generated by the scenery agent for testing.',
          keywords: ['mock', 'scenery', 'photo']
        })
      }
    };
  }
};

const researchAgent = {
  invoke: async (_messages) => {
    return {
      kwargs: {
        content: JSON.stringify({
          caption: 'Mocked research caption',
          description: 'This is a mocked description generated by the research agent for testing.',
          keywords: ['mock', 'research']
        })
      }
    };
  }
};

module.exports = {
  routerAgent,
  sceneryAgent,
  researchAgent,
  ROUTER_SYSTEM_PROMPT: 'ROUTER_SYSTEM_PROMPT (mock)',
  SCENERY_SYSTEM_PROMPT: 'SCENERY_SYSTEM_PROMPT (mock)',
  RESEARCH_SYSTEM_PROMPT: 'RESEARCH_SYSTEM_PROMPT (mock)'
};
